# This file was generated by GoReleaser. DO NOT EDIT.
cask "refurb-sentry" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "b0a3e8c619d86c3e4ac8c3285d52c0d6f8976f59603c0f7299ae13ccbd35cbff"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb5e1a0173f215738f8357864972f30a3a57513ce02df0456a621bdd1eb77f0b"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a9e3a0f9534a7d60f4c84050af6c3af6a343ab7354257b3e0684375b789c3927"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "159cca149f4f7fcda5bf9cb2fefb4d55f96d92bcb6e75a65bd698a2e0bb59c8f"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "refurb-sentry"
  desc "Monitor Apple's Certified Refurbished store for listings, price drops and removals"
  homepage "https://github.com/hh-io/refurb-sentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refurb-sentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/refurb-sentry"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    refurb-sentry needs a config file. Start from the example:

      curl -fsSLO https://raw.githubusercontent.com/hh-io/refurb-sentry/main/configs/config.example.yaml
      BARK_KEY=your-bark-key refurb-sentry -config config.example.yaml -once -dry-run

    To keep it running in the background, install the launchd agent from
    the repo (this cask does not register one):

      https://github.com/hh-io/refurb-sentry/tree/main/deploy

    This build is not signed or notarised by Apple. The cask strips the
    quarantine attribute on install so the binary can run.
  EOS
end
