# This file was generated by GoReleaser. DO NOT EDIT.
cask "refurb-sentry" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "0ce8c5c34604bbe59fd5bcb6ac9396870c4fb7d515c11e54328aafc10bdb09b7"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04ec6dcf24ac742a489c9da24a9d64b2f8a42ff86d19f0df316a663b506ff7d9"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d9243707a8f347627a5e27ad0e07f4a74f1c74071d3ca4a03d00ff14842f8143"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "847521c77008f3a6bbd5cdfc1e66f39e6e4f60f54819151cd20440567cbce71c"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "refurb-sentry"
  desc "Monitor Apple's Certified Refurbished store for listings, price drops and removals"
  homepage "https://github.com/hh-io/refurb-sentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refurb-sentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/refurb-sentry"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    refurb-sentry needs a config file. Start from the example:

      curl -fsSLO https://raw.githubusercontent.com/hh-io/refurb-sentry/main/configs/config.example.yaml
      BARK_KEY=your-bark-key refurb-sentry -config config.example.yaml -once -dry-run

    To keep it running in the background, install the launchd agent from
    the repo (this cask does not register one):

      https://github.com/hh-io/refurb-sentry/tree/main/deploy

    This build is not signed or notarised by Apple. The cask strips the
    quarantine attribute on install so the binary can run.
  EOS
end
