# This file was generated by GoReleaser. DO NOT EDIT.
cask "refurb-sentry" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "58821aa8300e354a3b403369fd3d7b804ddfa5d03c581c750dca3f5ca3d02430"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0803ab0cf7607fbf00a279c453842e4b096db827018a13ddbb48f15d0b50d01f"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b685e1cc38024572a20147fdaa47023f26f8d3dd63f94f4fb6190e45700e034"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc074972cc61e0655a8392b0f5d74ffa541bdacc666e689dcf30308c7292d748"
      url "https://github.com/hh-io/refurb-sentry/releases/download/v#{version}/refurb-sentry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "refurb-sentry"
  desc "Monitor Apple's Certified Refurbished store for listings, price drops and removals"
  homepage "https://github.com/hh-io/refurb-sentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refurb-sentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/refurb-sentry"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    refurb-sentry needs a config file. Start from the example:

      curl -fsSLO https://raw.githubusercontent.com/hh-io/refurb-sentry/main/configs/config.example.yaml
      refurb-sentry -config config.example.yaml -once -dry-run

    To keep it running in the background, install the launchd agent from
    the repo (this cask does not register one):

      https://github.com/hh-io/refurb-sentry/tree/main/deploy

    This build is not signed or notarised by Apple. The cask strips the
    quarantine attribute on install so the binary can run.
  EOS
end
